name: xtopia-master
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - ipython
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - hvplot
  - pip
  - pytest
  - pip:
    - fastapi
