name: deep-learning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - ipython
  - ipykernel
  - numpy
  - pandas
  - tensorflow
  - scikit-learn
  - matplotlib
  - seaborn
  - hvplot
  - pip
  - pip:
    - mlflow
