<<<<<<< Updated upstream
name: deep-learning
=======
name: xtopia-master
>>>>>>> Stashed changes
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - ipython
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - hvplot
  - pip
  - pip:
    - fastapi
